INSERT INTO `Transcript` (`idItem`, `Account_idAccount`, `itemName`, `scores`, `describe`, `IDParent`, `scoresDefault`, `scoresMax`, `scoresStudent`, `scoresTeacher`) VALUES
('I.a.1', 'AAAA', '- Đi học đầy đủ, đúng giờ, nghiêm túc trong giờ học (Mỗi môn bị cấm thi trừ 03 điểm)', 0, '', 'I.a', 6, 6, 6, 0),
('I.b.1.1', 'AAAA', '- Có tham gia đề tài NCKH của sinh viên hoặc của Khoa và cấp tương đương, có xác nhận của Chủ nhiệm đề tài (Không tính bài tập, tiểu luận, đồ án môn học, luận văn...)', 0, '', 'I.b.1', 5, 5, 5, 0),
('I.b.1.2', 'AAAA', '- Có giấy khen về NCKH', 0, '', 'I.b.1', 0, 8, 0, 0),
('I.b.1.3', 'AAAA', '- Có bài báo trong và ngoài nước trong hoạt động NCKH.', 0, '', 'I.b.1', 0, 8, 0, 0),
('I.b.2.1', 'AAAA', '- Ngoại ngữ không chuyên/chứng chỉ A/chuẩn khung Châu Âu.', 0, '', 'I.b.2', 0, 3, 0, 0),
('I.b.2.2', 'AAAA', '- Chứng chỉ B/chuẩn khung Châu Âu.', 0, '', 'I.b.2', 0, 5, 0, 0),
('I.b.2.3', 'AAAA', '- Chứng chỉ C/chuẩn khung Châu Âu', 0, '', 'I.b.2', 0, 7, 0, 0),
('I.b.2.4', 'AAAA', '- Riếng chứng chỉ ngoại ngữ, Chứng nhận Toefl >= 500 điểm; IELTS >= 5.0', 0, '', 'I.b.2', 0, 10, 0, 0),
('I.b.3.1', 'AAAA', '- Có tham gia kỳ thi', 0, '', 'I.b.3', 0, 2, 0, 0),
('I.b.3.2', 'AAAA', '- Đạt giải cấp Trường', 0, '', 'I.b.3', 0, 4, 0, 0),
('I.b.3.3', 'AAAA', '- Đạt giải cấp cao hơn.', 0, '', 'I.b.3', 0, 7, 0, 0),
('I.c.1', 'AAAA', '- Không vi phạm quy chế về thi, kiểm tra (Mỗi lần vi phạm trừ 03 điểm)', 0, '', 'I.c', 6, 6, 0, 0),
('I.d.1', 'AAAA', '- Có cố gắng, vượt khó trong học tập (có ĐTB học kỳ sau lớn hơn học kỳ trước đó; đối với SV năm thứ nhất, học kỳ I không có điểm dưới 4)', 0, '', 'I.d', 2, 2, 0, 0),
('I.e.1.1', 'AAAA', '- Điểm trung bình chung học kỳ (ĐTBCHK) đạt >= 3,60', 0, '', 'I.e.1', 0, 8, 0, 0),
('I.e.1.2', 'AAAA', '- ĐTBCHK đạt từ 3,20 đến 3,59', 0, '', 'I.e.1', 6, 6, 0, 0),
('I.e.1.3', 'AAAA', '- ĐTBCHK đạt từ 2,50 đến 3,19', 0, '', 'I.e.1', 0, 4, 0, 0),
('I.e.1.4', 'AAAA', '- ĐTBCHK đạt từ 2,00 đến 2,49', 0, '', 'I.e.1', 0, 2, 0, 0),
('II.a.1', 'AAAA', '- Không vi phạm và có ý thức tham gia thực hiện nghiêm túc các quy định của Lớp, nội quy, quy chế của trường, Khoa và các tổ chức trong nhà trường (Mỗi lần vắng trừ 03 điểm)', 0, '', 'II.a', 15, 15, 0, 0),
('II.b.1.1', 'AAAA', '- Giữ gìn an ninh, trật tự nơi công cộng có xác nhận của Đoàn khoa.', 0, '', 'II.b.1', 0, 10, 0, 0),
('II.b.1.2', 'AAAA', '- Giữ gìn vệ sinh, bảo vệ cảnh quan môi trường, nếp sống văn minh (có xác nhận của đoàn thể, Khoa, trường ...)', 0, '', 'II.b.1', 0, 10, 0, 0),
('III.a.1', 'AAAA', ' - Tham gia đầy đủ các hoạt động chính trị, xã hội, văn hóa, văn nghệ, thể thao các cấp từ Lớp, Chi hội, Chi đoàn trở lên tổ chức (Mỗi lần vắng trừ 02 điểm từ cấp đơn vị lớp trở lên).', 0, '', 'III.a', 12, 12, 0, 0),
('III.a.2', 'AAAA', ' - Lực lượng nồng cốt của phong trào', 0, '', 'III.a', 0, 5, 0, 0),
('III.b.1.1', 'AAAA', '- Cấp Bộ môn, Chi đoàn, Chi hội, Đội, Nhóm', 0, '', 'III.b.1', 0, 3, 0, 0),
('III.b.1.2', 'AAAA', '- Cấp Khoa (và tương đương), trường.', 0, '', 'III.b.1', 0, 5, 0, 0),
('III.c', 'AAAA', 'c. Tham gia tuyên truyền, phòng chống tội phạm và các tệ nạn xã hội.', 0, '', 'III', 0, 0, 0, 0),
('III.c.1.1', 'AAAA', '- Quyết định khen thưởng của Đoàn Khoa (và tương đương)', 0, '', 'III.c.1', 0, 6, 0, 0),
('III.c.1.2', 'AAAA', '- Giấy khen cấp Trường.', 0, '', 'III.c.1', 0, 8, 0, 0),
('III.c.1.3', 'AAAA', '- Giấy khen cấp cao hơn.', 0, '', 'III.c.1', 0, 10, 0, 0),
('IV.a.1', 'AAAA', '- Không vi phạm pháp luật của Nhà nước (Nếu vi phạm pháp luật sẽ bị điểm 00 (điểm không)).', 0, '', 'IV.a', 10, 10, 0, 0),
('IV.a.2', 'AAAA', '- Tích cực tham gia tuyên truyền các chủ trương của Đảng, chính sách, pháp luật của Nhà nước trong cộng đồng.', 0, '', 'IV.a', 5, 5, 0, 0),
('IV.b.1', 'AAAA', '  - Tham gia đội nhóm sinh hoạt hướng đên lợi ích cộng đồng (tham gia công tác xã hội ở trường, nơi cư trú, địa phương). (Mỗi đợt tham gia được cộng 02 điểm).', 0, '', 'IV.b', 2, 10, 0, 0),
('IV.c.1', 'AAAA', '- Có tinh thần giúp đỡ bạn bè trong học tập, trong cuộc sống.', 0, '', 'IV.c', 5, 5, 0, 0),
('V.a.1', 'AAAA', '- Lớp trưởng, Bí thư Chi đoàn, Ủy viên BCH đoàn thể cấp cao hơn Chi đoàn, BCH Hội sinh viên Trường, Liên Chi hội trưởng, Chi hội trưởng, Đội trưởng các Đội, Nhóm, Câu lạc bộ từ cấp khoa và tương đương.', 0, '', 'V.a', 10, 10, 0, 0),
('V.b.1', 'AAAA', ' - Là thành viên của Ban Cán sự lớp, Ban Chấp hành chi đoàn, Ban chấp hành Liên Chi hội SV, Chi hội SV Trường (trừ các thành viên nêu mục trên), Đội SV an ninh xung kích (KTX), Hội đồng tự quản KTX (gồm Chủ tịch và các Trưởng nhóm chuyên môn), Hội đồng tự quản ngoại trú, Nhà trưởng KTX, Cụm trưởng khu nhà trọ đã hoàn thành nhiệm vụ được giao', 0, '', 'V.b', 0, 8, 0, 0),
('V.b.2', 'AAAA', ' - Là thành viên của các Ban chuyên môn Đoàn, Hội sinh viên trường hoàn thành nhiệm vụ có xác nhận của Đoàn hoặc Hội sinh viên.', 0, '', 'V.b', 0, 8, 0, 0),
('V.c.1', 'AAAA', '  - Tích cực tham gia hỗ trợ các hoạt động, phong trào của cấp Khoa, sự kiện chung của nhà trường có xác nhận của đơn vị tổ chức sự kiện (Mỗi đợt tham gia được cộng 01 điểm).', 0, '', 'V.c', 0, 6, 0, 0),
('V.d.1', 'AAAA', '- Được kết nạp Đảng, hoặc được công nhận Đoàn viên ưu tú.', 0, '', 'V.d', 0, 6, 0, 0),
('V.d.2', 'AAAA', '- Đạt danh hiệu sinh viên 5 tốt cấp trường trở lên.', 0, '', 'V.d', 0, 6, 0, 0),
('V.d.3', 'AAAA', '- Phân loại Đảng viên được xếp loại mức 2', 0, '', 'V.d', 0, 5, 0, 0);